# Generated by Django 4.1.4 on 2022-12-28 12:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCategory",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименовние категории"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категрия блюда",
                "verbose_name_plural": "Категория блюд",
                "db_table": "fd_db",
            },
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Наименовние ингредиента"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингредиент",
                "verbose_name_plural": "Ингредиенты",
                "db_table": "topping_db",
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название блюда"),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="описание блюда"),
                ),
                ("price", models.IntegerField()),
                ("is_vegan", models.BooleanField(default=True)),
                ("is_special", models.BooleanField(default=True)),
                (
                    "category_id",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="foods.foodcategory",
                    ),
                ),
                (
                    "toppings",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="foods.topping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блюдо",
                "verbose_name_plural": "Блюда",
                "db_table": "food_db",
            },
        ),
    ]
