# Generated by Django 4.1.4 on 2022-12-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodcategory",
            name="is_publish",
            field=models.BooleanField(default=True),
        ),
    ]
