# Generated by Django 4.1.4 on 2022-12-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0002_foodcategory_is_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodcategory",
            name="is_publish",
            field=models.BooleanField(),
        ),
    ]
